twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        horaire: '@App\Twig\HoraireExtension'
    
when@test:
    twig:
        strict_variables: true
